// Copyright 2021 The KCL Authors. All rights reserved.

package list

import (
	"testing"
)

func TestDepParser_parseImport(t *testing.T) {
	for i, tt := range t_parser_import_list {
		imports := parseImport(tt.code)
		if len(imports) != tt.imports {
			t.Fatalf("%d: parseImport failed, imports = %v, code = %s", i, imports, tt.code)
		}
	}
}

var t_parser_import_list = []struct {
	imports int
	code    string
}{
	{
		imports: 1,
		code: `
	"""abc"""
	import base.pkg.kusion_kubernetes.apimachinery.apis
	`,
	},
	{
		imports: 1,
		code: `
	'''abc'''
	import base.pkg.kusion_kubernetes.apimachinery.apis
	`,
	},
	{
		imports: 1,
		code: `
	"""
	This is the mutating_webhook_configuration module in kusion_kubernetes.api.admissionregistration.v1beta1 package.
	This file was generated by the KCL auto-gen tool. DO NOT EDIT.
	Editing this file might prove futile when you re-run the KCL auto-gen generate command.
	"""
	import base.pkg.kusion_kubernetes.apimachinery.apis
	`,
	},
	{
		imports: 2,
		code: `
		"""
		This file was generated by the KCL auto-gen tool. DO NOT EDIT.
		Editing this file might prove futile when you re-run the KCL auto-gen generate command.
		"""
		import base.pkg.kusion_kubernetes.apimachinery.apis
		import base.pkg.kusion_kubernetes.api.core.v1
		`,
	},
	{
		imports: 1,
		code: `
		'''
		This file was generated by the KCL auto-gen tool. DO NOT EDIT.
		Editing this file might prove futile when you re-run the KCL auto-gen generate command.
		"""
		import base.pkg.kusion_kubernetes.apimachinery.apis
		import base.pkg.kusion_kubernetes.api.core.v1
		'''
		import abc
		`,
	},
	{
		imports: 1,
		code: `
		'aaa'
		import kcl_plugin.hello
		a = 2
		`,
	},
	{
		imports: 1,
		code: `
		"aaa"
		import kcl_plugin.hello
		a = 2
		`,
	},
}
