// Code generated by protoc-gen-protorpc. DO NOT EDIT.
//
// plugin: https://github.com/chai2010/protorpc/tree/master/protoc-gen-plugin
// plugin: https://github.com/chai2010/protorpc/tree/master/protoc-gen-protorpc
//
// source: gpyrpc.proto

package gpyrpc

import (
	"fmt"
	"io"
	"log"
	"net"
	"net/rpc"
	"time"

	"github.com/chai2010/protorpc"
	"google.golang.org/protobuf/proto"
)

var (
	_ = fmt.Sprint
	_ = io.Reader(nil)
	_ = log.Print
	_ = net.Addr(nil)
	_ = rpc.Call{}
	_ = time.Second

	_ = proto.String
	_ = protorpc.Dial
)

type PROTORPC_BuiltinService interface {
	Ping(in *PingArgs, out *PingResult) error
	ListMethod(in *ListMethodArgs, out *ListMethodResult) error
}

// PROTORPC_AcceptBuiltinServiceClient accepts connections on the listener and serves requests
// for each incoming connection.  Accept blocks; the caller typically
// invokes it in a go statement.
func PROTORPC_AcceptBuiltinServiceClient(lis net.Listener, x PROTORPC_BuiltinService) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("BuiltinService", x); err != nil {
		log.Fatal(err)
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeCodec(protorpc.NewServerCodec(conn))
	}
}

// PROTORPC_RegisterBuiltinService publish the given PROTORPC_BuiltinService implementation on the server.
func PROTORPC_RegisterBuiltinService(srv *rpc.Server, x PROTORPC_BuiltinService) error {
	if err := srv.RegisterName("BuiltinService", x); err != nil {
		return err
	}
	return nil
}

// PROTORPC_NewBuiltinServiceServer returns a new PROTORPC_BuiltinService Server.
func PROTORPC_NewBuiltinServiceServer(x PROTORPC_BuiltinService) *rpc.Server {
	srv := rpc.NewServer()
	if err := srv.RegisterName("BuiltinService", x); err != nil {
		log.Fatal(err)
	}
	return srv
}

// PROTORPC_ListenAndServeBuiltinService listen announces on the local network address laddr
// and serves the given BuiltinService implementation.
func PROTORPC_ListenAndServeBuiltinService(network, addr string, x PROTORPC_BuiltinService) error {
	lis, err := net.Listen(network, addr)
	if err != nil {
		return err
	}
	defer lis.Close()

	srv := rpc.NewServer()
	if err := srv.RegisterName("BuiltinService", x); err != nil {
		return err
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeCodec(protorpc.NewServerCodec(conn))
	}
}

// PROTORPC_ServeBuiltinService serves the given PROTORPC_BuiltinService implementation.
func PROTORPC_ServeBuiltinService(conn io.ReadWriteCloser, x PROTORPC_BuiltinService) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("BuiltinService", x); err != nil {
		log.Fatal(err)
	}
	srv.ServeCodec(protorpc.NewServerCodec(conn))
}

type PROTORPC_BuiltinServiceClient struct {
	*rpc.Client
}

// PROTORPC_NewBuiltinServiceClient returns a PROTORPC_BuiltinService stub to handle
// requests to the set of PROTORPC_BuiltinService at the other end of the connection.
func PROTORPC_NewBuiltinServiceClient(conn io.ReadWriteCloser) *PROTORPC_BuiltinServiceClient {
	c := rpc.NewClientWithCodec(protorpc.NewClientCodec(conn))
	return &PROTORPC_BuiltinServiceClient{c}
}

func (c *PROTORPC_BuiltinServiceClient) Ping(in *PingArgs) (out *PingResult, err error) {
	if in == nil {
		in = new(PingArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(PingResult)
	if err = c.Call("BuiltinService.Ping", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_BuiltinServiceClient) AsyncPing(in *PingArgs, out *PingResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(PingArgs)
	}
	return c.Go(
		"BuiltinService.Ping",
		in, out,
		done,
	)
}

func (c *PROTORPC_BuiltinServiceClient) ListMethod(in *ListMethodArgs) (out *ListMethodResult, err error) {
	if in == nil {
		in = new(ListMethodArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ListMethodResult)
	if err = c.Call("BuiltinService.ListMethod", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_BuiltinServiceClient) AsyncListMethod(in *ListMethodArgs, out *ListMethodResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ListMethodArgs)
	}
	return c.Go(
		"BuiltinService.ListMethod",
		in, out,
		done,
	)
}

// PROTORPC_DialBuiltinService connects to an PROTORPC_BuiltinService at the specified network address.
func PROTORPC_DialBuiltinService(network, addr string) (*PROTORPC_BuiltinServiceClient, error) {
	c, err := protorpc.Dial(network, addr)
	if err != nil {
		return nil, err
	}
	return &PROTORPC_BuiltinServiceClient{c}, nil
}

// PROTORPC_DialBuiltinServiceTimeout connects to an PROTORPC_BuiltinService at the specified network address.
func PROTORPC_DialBuiltinServiceTimeout(network, addr string, timeout time.Duration) (*PROTORPC_BuiltinServiceClient, error) {
	c, err := protorpc.DialTimeout(network, addr, timeout)
	if err != nil {
		return nil, err
	}
	return &PROTORPC_BuiltinServiceClient{c}, nil
}

type PROTORPC_KclvmService interface {
	Ping(in *PingArgs, out *PingResult) error
	ExecProgram(in *ExecProgramArgs, out *ExecProgramResult) error
	// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
	BuildProgram(in *BuildProgramArgs, out *BuildProgramResult) error
	// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
	ExecArtifact(in *ExecArtifactArgs, out *ExecProgramResult) error
	ParseProgram(in *ParseProgramArgs, out *ParseProgramResult) error
	ListOptions(in *ParseProgramArgs, out *ListOptionsResult) error
	ListVariables(in *ListVariablesArgs, out *ListVariablesResult) error
	LoadPackage(in *LoadPackageArgs, out *LoadPackageResult) error
	FormatCode(in *FormatCodeArgs, out *FormatCodeResult) error
	FormatPath(in *FormatPathArgs, out *FormatPathResult) error
	LintPath(in *LintPathArgs, out *LintPathResult) error
	OverrideFile(in *OverrideFileArgs, out *OverrideFileResult) error
	GetSchemaTypeMapping(in *GetSchemaTypeMappingArgs, out *GetSchemaTypeMappingResult) error
	ValidateCode(in *ValidateCodeArgs, out *ValidateCodeResult) error
	ListDepFiles(in *ListDepFilesArgs, out *ListDepFilesResult) error
	LoadSettingsFiles(in *LoadSettingsFilesArgs, out *LoadSettingsFilesResult) error
	Rename(in *RenameArgs, out *RenameResult) error
	RenameCode(in *RenameCodeArgs, out *RenameCodeResult) error
	Test(in *TestArgs, out *TestResult) error
	UpdateDependencies(in *UpdateDependenciesArgs, out *UpdateDependenciesResult) error
	GetVersion(in *GetVersionArgs, out *GetVersionResult) error
}

// PROTORPC_AcceptKclvmServiceClient accepts connections on the listener and serves requests
// for each incoming connection.  Accept blocks; the caller typically
// invokes it in a go statement.
func PROTORPC_AcceptKclvmServiceClient(lis net.Listener, x PROTORPC_KclvmService) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("KclvmService", x); err != nil {
		log.Fatal(err)
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeCodec(protorpc.NewServerCodec(conn))
	}
}

// PROTORPC_RegisterKclvmService publish the given PROTORPC_KclvmService implementation on the server.
func PROTORPC_RegisterKclvmService(srv *rpc.Server, x PROTORPC_KclvmService) error {
	if err := srv.RegisterName("KclvmService", x); err != nil {
		return err
	}
	return nil
}

// PROTORPC_NewKclvmServiceServer returns a new PROTORPC_KclvmService Server.
func PROTORPC_NewKclvmServiceServer(x PROTORPC_KclvmService) *rpc.Server {
	srv := rpc.NewServer()
	if err := srv.RegisterName("KclvmService", x); err != nil {
		log.Fatal(err)
	}
	return srv
}

// PROTORPC_ListenAndServeKclvmService listen announces on the local network address laddr
// and serves the given KclvmService implementation.
func PROTORPC_ListenAndServeKclvmService(network, addr string, x PROTORPC_KclvmService) error {
	lis, err := net.Listen(network, addr)
	if err != nil {
		return err
	}
	defer lis.Close()

	srv := rpc.NewServer()
	if err := srv.RegisterName("KclvmService", x); err != nil {
		return err
	}

	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Fatalf("lis.Accept(): %v\n", err)
		}
		go srv.ServeCodec(protorpc.NewServerCodec(conn))
	}
}

// PROTORPC_ServeKclvmService serves the given PROTORPC_KclvmService implementation.
func PROTORPC_ServeKclvmService(conn io.ReadWriteCloser, x PROTORPC_KclvmService) {
	srv := rpc.NewServer()
	if err := srv.RegisterName("KclvmService", x); err != nil {
		log.Fatal(err)
	}
	srv.ServeCodec(protorpc.NewServerCodec(conn))
}

type PROTORPC_KclvmServiceClient struct {
	*rpc.Client
}

// PROTORPC_NewKclvmServiceClient returns a PROTORPC_KclvmService stub to handle
// requests to the set of PROTORPC_KclvmService at the other end of the connection.
func PROTORPC_NewKclvmServiceClient(conn io.ReadWriteCloser) *PROTORPC_KclvmServiceClient {
	c := rpc.NewClientWithCodec(protorpc.NewClientCodec(conn))
	return &PROTORPC_KclvmServiceClient{c}
}

func (c *PROTORPC_KclvmServiceClient) Ping(in *PingArgs) (out *PingResult, err error) {
	if in == nil {
		in = new(PingArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(PingResult)
	if err = c.Call("KclvmService.Ping", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncPing(in *PingArgs, out *PingResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(PingArgs)
	}
	return c.Go(
		"KclvmService.Ping",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ExecProgram(in *ExecProgramArgs) (out *ExecProgramResult, err error) {
	if in == nil {
		in = new(ExecProgramArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ExecProgramResult)
	if err = c.Call("KclvmService.ExecProgram", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncExecProgram(in *ExecProgramArgs, out *ExecProgramResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ExecProgramArgs)
	}
	return c.Go(
		"KclvmService.ExecProgram",
		in, out,
		done,
	)
}

// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
func (c *PROTORPC_KclvmServiceClient) BuildProgram(in *BuildProgramArgs) (out *BuildProgramResult, err error) {
	if in == nil {
		in = new(BuildProgramArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(BuildProgramResult)
	if err = c.Call("KclvmService.BuildProgram", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
func (c *PROTORPC_KclvmServiceClient) AsyncBuildProgram(in *BuildProgramArgs, out *BuildProgramResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(BuildProgramArgs)
	}
	return c.Go(
		"KclvmService.BuildProgram",
		in, out,
		done,
	)
}

// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
func (c *PROTORPC_KclvmServiceClient) ExecArtifact(in *ExecArtifactArgs) (out *ExecProgramResult, err error) {
	if in == nil {
		in = new(ExecArtifactArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ExecProgramResult)
	if err = c.Call("KclvmService.ExecArtifact", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

// Depreciated: Please use the env.EnableFastEvalMode() and c.ExecuteProgram method and will be removed in v0.11.0.
func (c *PROTORPC_KclvmServiceClient) AsyncExecArtifact(in *ExecArtifactArgs, out *ExecProgramResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ExecArtifactArgs)
	}
	return c.Go(
		"KclvmService.ExecArtifact",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ParseFile(in *ParseFileArgs) (out *ParseFileResult, err error) {
	if in == nil {
		in = new(ParseFileArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ParseFileResult)
	if err = c.Call("KclvmService.ParseFile", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncParseFile(in *ParseFileArgs, out *ParseFileResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ParseFileArgs)
	}
	return c.Go(
		"KclvmService.ParseFile",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ParseProgram(in *ParseProgramArgs) (out *ParseProgramResult, err error) {
	if in == nil {
		in = new(ParseProgramArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ParseProgramResult)
	if err = c.Call("KclvmService.ParseProgram", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncParseProgram(in *ParseProgramArgs, out *ParseProgramResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ParseProgramArgs)
	}
	return c.Go(
		"KclvmService.ParseProgram",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ListOptions(in *ParseProgramArgs) (out *ListOptionsResult, err error) {
	if in == nil {
		in = new(ParseProgramArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ListOptionsResult)
	if err = c.Call("KclvmService.ListOptions", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncListOptions(in *ParseProgramArgs, out *ListOptionsResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ParseProgramArgs)
	}
	return c.Go(
		"KclvmService.ListOptions",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ListVariables(in *ListVariablesArgs) (out *ListVariablesResult, err error) {
	if in == nil {
		in = new(ListVariablesArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ListVariablesResult)
	if err = c.Call("KclvmService.ListVariables", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncListVariables(in *ListVariablesArgs, out *ListVariablesResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ListVariablesArgs)
	}
	return c.Go(
		"KclvmService.ListVariables",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) LoadPackage(in *LoadPackageArgs) (out *LoadPackageResult, err error) {
	if in == nil {
		in = new(LoadPackageArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(LoadPackageResult)
	if err = c.Call("KclvmService.LoadPackage", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncLoadPackage(in *LoadPackageArgs, out *LoadPackageResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(LoadPackageArgs)
	}
	return c.Go(
		"KclvmService.LoadPackage",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) FormatCode(in *FormatCodeArgs) (out *FormatCodeResult, err error) {
	if in == nil {
		in = new(FormatCodeArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(FormatCodeResult)
	if err = c.Call("KclvmService.FormatCode", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncFormatCode(in *FormatCodeArgs, out *FormatCodeResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(FormatCodeArgs)
	}
	return c.Go(
		"KclvmService.FormatCode",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) FormatPath(in *FormatPathArgs) (out *FormatPathResult, err error) {
	if in == nil {
		in = new(FormatPathArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(FormatPathResult)
	if err = c.Call("KclvmService.FormatPath", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncFormatPath(in *FormatPathArgs, out *FormatPathResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(FormatPathArgs)
	}
	return c.Go(
		"KclvmService.FormatPath",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) LintPath(in *LintPathArgs) (out *LintPathResult, err error) {
	if in == nil {
		in = new(LintPathArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(LintPathResult)
	if err = c.Call("KclvmService.LintPath", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncLintPath(in *LintPathArgs, out *LintPathResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(LintPathArgs)
	}
	return c.Go(
		"KclvmService.LintPath",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) OverrideFile(in *OverrideFileArgs) (out *OverrideFileResult, err error) {
	if in == nil {
		in = new(OverrideFileArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(OverrideFileResult)
	if err = c.Call("KclvmService.OverrideFile", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncOverrideFile(in *OverrideFileArgs, out *OverrideFileResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(OverrideFileArgs)
	}
	return c.Go(
		"KclvmService.OverrideFile",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) GetSchemaTypeMapping(in *GetSchemaTypeMappingArgs) (out *GetSchemaTypeMappingResult, err error) {
	if in == nil {
		in = new(GetSchemaTypeMappingArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(GetSchemaTypeMappingResult)
	if err = c.Call("KclvmService.GetSchemaTypeMapping", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncGetSchemaTypeMapping(in *GetSchemaTypeMappingArgs, out *GetSchemaTypeMappingResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(GetSchemaTypeMappingArgs)
	}
	return c.Go(
		"KclvmService.GetSchemaTypeMapping",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ValidateCode(in *ValidateCodeArgs) (out *ValidateCodeResult, err error) {
	if in == nil {
		in = new(ValidateCodeArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ValidateCodeResult)
	if err = c.Call("KclvmService.ValidateCode", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncValidateCode(in *ValidateCodeArgs, out *ValidateCodeResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ValidateCodeArgs)
	}
	return c.Go(
		"KclvmService.ValidateCode",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) ListDepFiles(in *ListDepFilesArgs) (out *ListDepFilesResult, err error) {
	if in == nil {
		in = new(ListDepFilesArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(ListDepFilesResult)
	if err = c.Call("KclvmService.ListDepFiles", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncListDepFiles(in *ListDepFilesArgs, out *ListDepFilesResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(ListDepFilesArgs)
	}
	return c.Go(
		"KclvmService.ListDepFiles",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) LoadSettingsFiles(in *LoadSettingsFilesArgs) (out *LoadSettingsFilesResult, err error) {
	if in == nil {
		in = new(LoadSettingsFilesArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(LoadSettingsFilesResult)
	if err = c.Call("KclvmService.LoadSettingsFiles", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncLoadSettingsFiles(in *LoadSettingsFilesArgs, out *LoadSettingsFilesResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(LoadSettingsFilesArgs)
	}
	return c.Go(
		"KclvmService.LoadSettingsFiles",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) Rename(in *RenameArgs) (out *RenameResult, err error) {
	if in == nil {
		in = new(RenameArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(RenameResult)
	if err = c.Call("KclvmService.Rename", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncRename(in *RenameArgs, out *RenameResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(RenameArgs)
	}
	return c.Go(
		"KclvmService.RenameCode",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) RenameCode(in *RenameCodeArgs) (out *RenameCodeResult, err error) {
	if in == nil {
		in = new(RenameCodeArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(RenameCodeResult)
	if err = c.Call("KclvmService.RenameCode", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncRenameCode(in *RenameCodeArgs, out *RenameCodeResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(RenameCodeArgs)
	}
	return c.Go(
		"KclvmService.RenameCode",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) Test(in *TestArgs) (out *TestResult, err error) {
	if in == nil {
		in = new(TestArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(TestResult)
	if err = c.Call("KclvmService.Test", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncTest(in *TestArgs, out *TestResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(TestArgs)
	}
	return c.Go(
		"KclvmService.Test",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) UpdateDependencies(in *UpdateDependenciesArgs) (out *UpdateDependenciesResult, err error) {
	if in == nil {
		in = new(UpdateDependenciesArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(UpdateDependenciesResult)
	if err = c.Call("KclvmService.UpdateDependencies", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncUpdateDependencies(in *UpdateDependenciesArgs, out *UpdateDependenciesResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(UpdateDependenciesArgs)
	}
	return c.Go(
		"KclvmService.UpdateDependencies",
		in, out,
		done,
	)
}

func (c *PROTORPC_KclvmServiceClient) GetVersion(in *GetVersionArgs) (out *GetVersionResult, err error) {
	if in == nil {
		in = new(GetVersionArgs)
	}

	type Validator interface {
		Validate() error
	}
	if x, ok := proto.Message(in).(Validator); ok {
		if err := x.Validate(); err != nil {
			return nil, err
		}
	}

	out = new(GetVersionResult)
	if err = c.Call("KclvmService.GetVersion", in, out); err != nil {
		return nil, err
	}

	if x, ok := proto.Message(out).(Validator); ok {
		if err := x.Validate(); err != nil {
			return out, err
		}
	}

	return out, nil
}

func (c *PROTORPC_KclvmServiceClient) AsyncGetVersion(in *GetVersionArgs, out *GetVersionResult, done chan *rpc.Call) *rpc.Call {
	if in == nil {
		in = new(GetVersionArgs)
	}
	return c.Go(
		"KclvmService.GetVersion",
		in, out,
		done,
	)
}

// PROTORPC_DialKclvmService connects to an PROTORPC_KclvmService at the specified network address.
func PROTORPC_DialKclvmService(network, addr string) (*PROTORPC_KclvmServiceClient, error) {
	c, err := protorpc.Dial(network, addr)
	if err != nil {
		return nil, err
	}
	return &PROTORPC_KclvmServiceClient{c}, nil
}

// PROTORPC_DialKclvmServiceTimeout connects to an PROTORPC_KclvmService at the specified network address.
func PROTORPC_DialKclvmServiceTimeout(network, addr string, timeout time.Duration) (*PROTORPC_KclvmServiceClient, error) {
	c, err := protorpc.DialTimeout(network, addr, timeout)
	if err != nil {
		return nil, err
	}
	return &PROTORPC_KclvmServiceClient{c}, nil
}
